spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: ravi
    password: ravi
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true

    
    
